-- ============================================================
-- {VERSION}/{NNN}: [Mo ta thay doi]
-- Date:   YYYY-MM-DD
-- Author: [ten]
-- ============================================================
-- [Giai thich tai sao can thay doi nay]
-- ============================================================

-- === CAU TRUC THU MUC ===
--
-- db/changelog/
-- ├── _init/                        ← tracker table (tu dong)
-- ├── 1.0.0/                        ← version 1.0.0
-- │   ├── 001__create_xxx.sql
-- │   └── 002__add_yyy.sql
-- ├── 1.1.0/                        ← version 1.1.0
-- │   ├── 001__alter_xxx.sql
-- │   └── 002__seed_data.sql
-- └── TEMPLATE.sql
--
-- Quy tac:
--   - Thu muc = version (semver: major.minor.patch)
--   - File = 3 so thu tu + 2 gach duoi + mo ta: 001__ten_mo_ta.sql
--   - Chay theo thu tu: sort version dir → sort file trong dir
--   - Xem trang thai: bash scripts/db-changelog.sh <ip> --status

-- === PATTERNS IDEMPOTENT (chay lai nhieu lan khong loi) ===
--
-- Them column (neu chua co):
--   SET @sql = (SELECT IF(
--       EXISTS (SELECT 1 FROM information_schema.COLUMNS
--               WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='xxx' AND COLUMN_NAME='yyy'),
--       'SELECT ''[SKIP] xxx.yyy already exists'' AS info;',
--       'ALTER TABLE xxx ADD COLUMN yyy VARCHAR(255) NULL;'
--   ));
--   PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
--
-- Them index (neu chua co):
--   SET @sql = (SELECT IF(
--       EXISTS (SELECT 1 FROM information_schema.STATISTICS
--               WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='xxx' AND INDEX_NAME='idx_xxx_yyy'),
--       'SELECT ''[SKIP] idx_xxx_yyy already exists'' AS info;',
--       'CREATE INDEX idx_xxx_yyy ON xxx(yyy);'
--   ));
--   PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
--
-- Tao table:
--   CREATE TABLE IF NOT EXISTS xxx (...);
--
-- Insert du lieu mac dinh / seed: dung REPLACE INTO
--   REPLACE INTO plans (id, name, price) VALUES
--   ('plan_free', 'Free', 0),
--   ('plan_pro', 'Pro', 99000);
--
-- Update data:
--   UPDATE xxx SET yyy = 'value' WHERE yyy IS NULL OR yyy = '';

-- === KHONG LAM ===
-- DROP TABLE, DROP COLUMN, TRUNCATE (tru khi co ly do + user cho phep)
-- Thay doi column type khi da co data (phai migrate data truoc)

-- [Viet SQL o day]

-- Verify
-- SELECT CONCAT('[OK] ', ...) AS result FROM ...;
